<?php
if ( !defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly
}

// Header Setings
CSF::createSection( $restlyThemeOption, array(
    'id'    => 'restly_header_settings',
    'title' => esc_html__( 'Header Settings', 'restly' ),
    'icon'  => 'fa fa-header',
) );

// Header Style
CSF::createSection( $restlyThemeOption, array(
    'parent' => 'restly_header_settings',
    'title'  => esc_html__( 'Header Style', 'restly' ),
    'icon'   => 'fas fa-arrow-right',
    'fields' => array(
        array(
            'id'       => 'restly_header_styles',
            'type'     => 'image_select',
            'title'    => esc_html__( 'Select Style', 'restly' ),
            'options'  => array(
                'one'   => get_theme_file_uri( 'assets/image/header-1.jpg' ),
                'two'   => get_theme_file_uri( 'assets/image/header-2.jpg' ),
                'three' => get_theme_file_uri( 'assets/image/header-3.jpg' ),
            ),
            'default'  => 'three',
            'subtitle' => esc_html__( 'Choose Your Header Style For Global', 'restly' ),
        ),
    ),
) );
// End Header Style

// Header Options
CSF::createSection( $restlyThemeOption, array(
    'parent' => 'restly_header_settings',
    'title'  => esc_html__( 'Top Header Options', 'restly' ),
    'icon'   => 'fas fa-arrow-right',
    'fields' => array(
        // A Subheading
        array(
            'type'    => 'subheading',
            'content' => esc_html__( 'Top Header Left', 'restly' ),
        ),
        array(
            'id'       => 'restly_top_left_header_group',
            'type'     => 'group',
            'title'    => esc_html__( 'Top Header Left Content', 'restly' ),
            'subtitle' => esc_html__( 'Add your Content forTop Header Left', 'restly' ),
            'fields'   => array(
                array(
                    'id'    => 'restly_left_topH_label',
                    'type'  => 'text',
                    'title' => esc_html__( 'Label', 'restly' ),
                ),
                array(
                    'id'            => 'restly_left_topH_dec',
                    'type'          => 'wp_editor',
                    'media_buttons' => false,
                    'height'        => '100px',
                    'title'         => esc_html__( 'Content', 'restly' ),
                    'desc'          => esc_html__( 'Please Add your content for Top Header Left Section', 'restly' ),
                ),
            ),
            'default'  => array(
                array(
                    'restly_left_topH_label' => esc_html__( 'Call Us:', 'restly' ),
                    'restly_left_topH_dec'   => esc_html__( '548978478', 'restly' ),
                ),
                array(
                    'restly_left_topH_label' => esc_html__( 'Email us:', 'restly' ),
                    'restly_left_topH_dec'   => esc_html__( 'demo@example.com', 'restly' ),
                ),
                array(
                    'restly_left_topH_label' => esc_html__( 'Our address:', 'restly' ),
                    'restly_left_topH_dec'   => esc_html__( '45 Dream street Austria', 'restly' ),
                ),
            ),
        ),

        array(
            'type'    => 'subheading',
            'content' => esc_html__( 'Header Top Right Section', 'restly' ),
        ),
        array(
            'id'      => 'restly_top_hopen_time',
            'type'    => 'fieldset',
            'title'   => esc_html__( 'Open Time', 'restly' ),
            'fields'  => array(
                array(
                    'id'    => 'restly_top_hopen_icon',
                    'type'  => 'icon',
                    'title' => esc_html__( 'Icon', 'restly' ),
                ),
                array(
                    'id'    => 'restly_top_hopen_text',
                    'type'  => 'text',
                    'title' => esc_html__( 'Text', 'restly' ),
                ),
            ),
            'default' => array(
                'restly_top_hopen_icon' => 'fas fa-clock',
                'restly_top_hopen_text' => esc_html__( '08:00 am - 06:00 pm', 'restly' ),
            ),
        ),
        array(
            'id'      => 'restly_header_top_right_socials',
            'type'    => 'group',
            'title'   => esc_html__( 'Select Social', 'restly' ),
            'fields'  => array(
                array(
                    'id'    => 'restly_top_hsocial_label',
                    'type'  => 'text',
                    'title' => esc_html__( 'Label', 'restly' ),
                ),
                array(
                    'id'    => 'restly_top_hsocial_icon',
                    'type'  => 'icon',
                    'title' => esc_html__( 'Icon', 'restly' ),
                ),
                array(
                    'id'    => 'restly_top_hsocial_link',
                    'type'  => 'text',
                    'title' => esc_html__( 'Link', 'restly' ),
                ),
            ),
            'default' => array(
                array(
                    'restly_top_hsocial_label' => esc_html__( 'Facebook', 'restly' ),
                    'restly_top_hsocial_icon'  => 'fab fa-facebook-f',
                    'restly_top_hsocial_link'  => esc_html__( '#', 'restly' ),
                ),
                array(
                    'restly_top_hsocial_label' => esc_html__( 'Twitter', 'restly' ),
                    'restly_top_hsocial_icon'  => 'fab fa-twitter',
                    'restly_top_hsocial_link'  => esc_html__( '#', 'restly' ),
                ),
                array(
                    'restly_top_hsocial_label' => esc_html__( 'Instagram', 'restly' ),
                    'restly_top_hsocial_icon'  => 'fab fa-instagram',
                    'restly_top_hsocial_link'  => esc_html__( '#', 'restly' ),
                ),
                array(
                    'restly_top_hsocial_label' => esc_html__( 'Pinterest', 'restly' ),
                    'restly_top_hsocial_icon'  => 'fab fa-pinterest-p',
                    'restly_top_hsocial_link'  => esc_html__( '#', 'restly' ),
                ),
            ),
        ),
    ),
) );
CSF::createSection( $restlyThemeOption, array(
    'parent' => 'restly_header_settings',
    'title'  => esc_html__( 'Header Main Options', 'restly' ),
    'icon'   => 'fas fa-arrow-right',
    'fields' => array(
        array(
            'id'         => 'restly_show_hlogo1',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable Logo', 'restly' ),
            'subtitle'   => esc_html__( 'Enable Logo Options if you need', 'restly' ),
            'default'    => true,
            'dependency' => array( 'restly_header_styles', '==', 'one', 'all' ),
        ),
        array(
            'id'         => 'restly_logo1',
            'type'       => 'media',
            'title'      => esc_html__( 'SIte Logo', 'restly' ),
            'subtitle'   => esc_html__( 'Upload Header Logo if you do not use Wordpress Default logo option ', 'restly' ),
            'library'    => 'image',
            'dependency' => array( 'restly_header_styles|restly_show_hlogo1', '==|==', 'one|true', 'all' ),
        ),
        array(
            'id'          => 'restly_header1_logo_bg',
            'type'        => 'color',
            'title'       => esc_html__( 'Logo Background Color', 'restly' ),
            'subtitle'    => esc_html__( 'Add Logo Background Color', 'restly' ),
            'default'     => '#104cba',
            'output'      => '.logo-area.logobg:after',
            'output_mode' => 'background-color',
            'dependency'  => array( 'restly_header_styles', '==', 'one', 'all' ),
        ),
        array(
            'type'       => 'submessage',
            'style'      => 'success',
            'content'    => esc_html__( 'Top Header Options', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'one', 'all' ),
        ),
        array(
            'id'         => 'restly_show_top_header',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable Top Header', 'restly' ),
            'subtitle'   => esc_html__( 'Enable Top Header Option', 'restly' ),
            'default'    => true,
            'dependency' => array( 'restly_header_styles', '==', 'one', 'all' ),
        ),
        array(
            'id'         => 'restly_top_header1_bg',
            'type'       => 'background',
            'title'      => esc_html__( 'Background', 'restly' ),
            'subtitle'   => esc_html__( 'Add Background Color or Image', 'restly' ),
            'dependency' => array( 'restly_header_styles|restly_show_top_header', '==|==', 'one|true', 'all' ),
            'default'    => array(
                'background-color' => '#e5eef6',
            ),
            'output'     => '.header-top',
        ),
        array(
            'id'         => 'restly_top_header1_label_c',
            'type'       => 'color',
            'title'      => esc_html__( 'Label Color', 'restly' ),
            'subtitle'   => esc_html__( 'Add Color for Header top Label', 'restly' ),
            'default'    => '#1d2c38',
            'dependency' => array( 'restly_header_styles|restly_show_top_header', '==|==', 'one|true', 'all' ),
            'output'     => '.header-top ul li span',
        ),
        array(
            'id'         => 'restly_top_header1_text_c',
            'type'       => 'color',
            'title'      => esc_html__( 'Text Color', 'restly' ),
            'subtitle'   => esc_html__( 'Add Color for Header top Content', 'restly' ),
            'default'    => '#1d2c38',
            'output'     => '.header-top ul li',
            'dependency' => array( 'restly_header_styles|restly_show_top_header', '==|==', 'one|true', 'all' ),
        ),
        array(
            'id'         => 'restly_top_header1_icon_c',
            'type'       => 'color',
            'title'      => esc_html__( 'Icon Color', 'restly' ),
            'subtitle'   => esc_html__( 'Withour Link Icon Color', 'restly' ),
            'default'    => '#104cba',
            'output'     => '.office-time i',
            'dependency' => array( 'restly_header_styles|restly_show_top_header', '==|==', 'one|true', 'all' ),
        ),
        array(
            'id'         => 'restly_top_header1_link_c',
            'type'       => 'link_color',
            'title'      => esc_html__( 'Link Color', 'restly' ),
            'subtitle'   => esc_html__( 'Add Color for Header top Links Normal and Hover', 'restly' ),
            'output'     => '.header-top ul li a',
            'default'    => array(
                'color' => '#1d2c38',
                'hover' => '#104cba',
            ),
            'dependency' => array( 'restly_header_styles|restly_show_top_header', '==|==', 'one|true', 'all' ),
        ),
        array(
            'type'       => 'submessage',
            'style'      => 'success',
            'content'    => esc_html__( 'Menu Section Options', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'one', 'all' ),
        ),
        array(
            'id'         => 'restly_top_header1_menu_ncolors',
            'type'       => 'link_color',
            'title'      => esc_html__( 'Menu Color', 'restly' ),
            'subtitle'   => esc_html__( 'Nav Menu Normal and Hover Color', 'restly' ),
            'output'     => '.main-navigation ul li a',
            'dependency' => array( 'restly_header_styles', '==', 'one', 'all' ),
            'default'    => array(
                'color' => '#1d2c38',
                'hover' => '#104cba',
            ),
        ),
        array(
            'id'         => 'restly_header1_menu_bg',
            'type'       => 'background',
            'title'      => esc_html__( 'Background', 'restly' ),
            'subtitle'   => esc_html__( 'Add Background Color for Menu Area', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'one', 'all' ),
            'default'    => array(
                'background-color' => '#ffffff',
            ),
            'output'     => '.header-one .main-header.header-fluid .navbar',
        ),
        array(
            'type'       => 'submessage',
            'style'      => 'info',
            'content'    => esc_html__( 'Sub menu Options', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'one', 'all' ),
        ),
        array(
            'id'         => 'restly_header1_menu_bg',
            'type'       => 'color_group',
            'title'      => esc_html__( 'Sub menu Colors', 'restly' ),
            'subtitle'   => esc_html__( 'Add SubMenu Color', 'restly' ),
            'options'    => array(
                'restly_hea1_submeni_bgc'     => esc_html__( 'Box Background', 'restly' ),
                'restly_hea1_submeni_textc'   => esc_html__( 'Text Color', 'restly' ),
                'restly_hea1_submeni_texthc'  => esc_html__( 'Text Hover/active Color', 'restly' ),
                'restly_hea1_submeni_texthbg' => esc_html__( 'Hover/active BG Color', 'restly' ),
            ),
            'default'    => array(
                'restly_hea1_submeni_bgc'     => '#ffffff',
                'restly_hea1_submeni_textc'   => '#1d2c38',
                'restly_hea1_submeni_texthc'  => '#ffffff',
                'restly_hea1_submeni_texthbg' => '#104cba',
            ),
            'dependency' => array( 'restly_header_styles', '==', 'one', 'all' ),
        ),
        array(
            'type'       => 'submessage',
            'style'      => 'info',
            'content'    => esc_html__( 'CTA Button Option', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'one', 'all' ),
        ),
        array(
            'id'         => 'restly_show_cta',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable CTA Button', 'restly' ),
            'subtitle'   => esc_html__( 'Enable Header CTA button if you need', 'restly' ),
            'default'    => true,
            'dependency' => array( 'restly_header_styles', '==', 'one', 'all' ),
        ),
        array(
            'id'          => 'restly_cta_bg',
            'type'        => 'color',
            'title'       => esc_html__( 'CTA Button Bg', 'restly' ),
            'subtitle'    => esc_html__( 'Add CTA Button Background Color', 'restly' ),
            'default'     => '#104cba',
            'output'      => '.header-one .button .theme-btns',
            'output_mode' => 'background-color',
            'dependency'  => array( 'restly_header_styles|restly_show_cta', '==|==', 'one|true', 'all' ),
        ),
        array(
            'id'          => 'restly_cta_bgh',
            'type'        => 'color',
            'title'       => esc_html__( 'CTA Button Hover Bg', 'restly' ),
            'subtitle'    => esc_html__( 'Add CTA Button Hover Background Color', 'restly' ),
            'default'     => '#1d2c38',
            'output'      => '.header-one .button .theme-btns:hover',
            'output_mode' => 'background-color',
            'dependency'  => array( 'restly_header_styles|restly_show_cta', '==|==', 'one|true', 'all' ),
        ),
        array(
            'id'         => 'restly_cta_text_color',
            'type'       => 'link_color',
            'title'      => esc_html__( 'CTA Button Text Color', 'restly' ),
            'subtitle'   => esc_html__( 'Add CTA Button Text Hover and Normal Color', 'restly' ),
            'output'     => '.header-one .button .theme-btns',
            'dependency' => array( 'restly_header_styles|restly_show_cta', '==|==', 'one|true', 'all' ),
            'default'    => array(
                'color' => '#ffffff',
                'hover' => '#ffffff',
            ),
        ),

        ////////////////////
        // Header Two Options //
        /////////////////////

        array(
            'id'         => 'restly_show_hlogo2',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable Logo', 'restly' ),
            'subtitle'   => esc_html__( 'Enable Logo Options if you need', 'restly' ),
            'default'    => true,
            'dependency' => array( 'restly_header_styles', '==', 'two', 'all' ),
        ),
        array(
            'id'         => 'restly_logo2',
            'type'       => 'media',
            'title'      => esc_html__( 'SIte Logo', 'restly' ),
            'subtitle'   => esc_html__( 'Upload Header Logo if you do not use Wordpress Default logo option ', 'restly' ),
            'library'    => 'image',
            'dependency' => array( 'restly_header_styles|restly_show_hlogo2', '==|==', 'two|true', 'all' ),
        ),
        array(
            'id'          => 'restly_header2_border_color',
            'type'        => 'color',
            'title'       => esc_html__( 'Border Color', 'restly' ),
            'subtitle'    => esc_html__( 'Add Header Border Color', 'restly' ),
            'default'     => '#4e597b',
            'dependency'  => array( 'restly_header_styles', '==', 'two', 'all' ),
            'output_mode' => 'border-color',
            'output'      => '.header-two .main-header.header-fluid,.header-two .main-header-right,.header-two .header-top',
        ),
        array(
            'type'       => 'submessage',
            'style'      => 'success',
            'content'    => esc_html__( 'Top Header Options', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'two', 'all' ),
        ),
        array(
            'id'         => 'restly_show_top_header2',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable Top Header', 'restly' ),
            'subtitle'   => esc_html__( 'Enable Top Header Option', 'restly' ),
            'default'    => true,
            'dependency' => array( 'restly_header_styles', '==', 'two', 'all' ),
        ),
        array(
            'id'         => 'restly_top_header2_bg',
            'type'       => 'background',
            'title'      => esc_html__( 'Background', 'restly' ),
            'subtitle'   => esc_html__( 'Add Background Color or Image', 'restly' ),
            'dependency' => array( 'restly_header_styles|restly_show_top_header2', '==|==', 'two|true', 'all' ),
            'output'     => '.header-two .header-top',
        ),
        array(
            'id'         => 'restly_top_header2_label_c',
            'type'       => 'color',
            'title'      => esc_html__( 'Label Color', 'restly' ),
            'subtitle'   => esc_html__( 'Add Color for Header top Label', 'restly' ),
            'default'    => '#ffffff',
            'dependency' => array( 'restly_header_styles|restly_show_top_header2', '==|==', 'two|true', 'all' ),
            'output'     => '.header-two .header-top ul li span',
        ),
        array(
            'id'         => 'restly_top_header2_text_c',
            'type'       => 'color',
            'title'      => esc_html__( 'Text Color', 'restly' ),
            'subtitle'   => esc_html__( 'Add Color for Header top Content', 'restly' ),
            'default'    => '#ffffff',
            'output'     => '.header-two .header-top ul li',
            'dependency' => array( 'restly_header_styles|restly_show_top_header2', '==|==', 'two|true', 'all' ),
        ),
        array(
            'id'         => 'restly_top_header2_icon_c',
            'type'       => 'color',
            'title'      => esc_html__( 'Icon Color', 'restly' ),
            'subtitle'   => esc_html__( 'Withour Link Icon Color', 'restly' ),
            'default'    => '#ffffff',
            'output'     => '.header-two .office-time i',
            'dependency' => array( 'restly_header_styles|restly_show_top_header2', '==|==', 'two|true', 'all' ),
        ),
        array(
            'id'         => 'restly_top_header2_link_c',
            'type'       => 'link_color',
            'title'      => esc_html__( 'Link Color', 'restly' ),
            'subtitle'   => esc_html__( 'Add Color for Header top Links Normal and Hover', 'restly' ),
            'output'     => '.header-two .header-top ul li a',
            'default'    => array(
                'color' => '#ffffff',
                'hover' => '#104cba',
            ),
            'dependency' => array( 'restly_header_styles|restly_show_top_header2', '==|==', 'two|true', 'all' ),
        ),
        array(
            'type'       => 'submessage',
            'style'      => 'success',
            'content'    => esc_html__( 'Menu Section Options', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'two', 'all' ),
        ),
        array(
            'id'         => 'restly_top_header2_menu_ncolors',
            'type'       => 'link_color',
            'title'      => esc_html__( 'Menu Color', 'restly' ),
            'subtitle'   => esc_html__( 'Nav Menu Normal and Hover Color', 'restly' ),
            'output'     => '.header-two .main-navigation ul li a',
            'dependency' => array( 'restly_header_styles', '==', 'two', 'all' ),
            'default'    => array(
                'color' => '#ffffff',
                'hover' => '#b0c2d7',
            ),
        ),
        array(
            'id'         => 'restly_header2_menu_bg',
            'type'       => 'background',
            'title'      => esc_html__( 'Background', 'restly' ),
            'subtitle'   => esc_html__( 'Add Background Color for Menu Area', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'two', 'all' ),
            'output'     => '.header-two .header-two .main-header.header-fluid .navbar',
        ),
        array(
            'type'       => 'submessage',
            'style'      => 'info',
            'content'    => esc_html__( 'Sub menu Options', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'two', 'all' ),
        ),
        array(
            'id'         => 'restly_header2_menu_bg',
            'type'       => 'color_group',
            'title'      => esc_html__( 'Sub menu Colors', 'restly' ),
            'subtitle'   => esc_html__( 'Add SubMenu Color', 'restly' ),
            'options'    => array(
                'restly_hea2_submeni_bgc'     => esc_html__( 'Box Background', 'restly' ),
                'restly_hea2_submeni_textc'   => esc_html__( 'Text Color', 'restly' ),
                'restly_hea2_submeni_texthc'  => esc_html__( 'Text Hover/active Color', 'restly' ),
                'restly_hea2_submeni_texthbg' => esc_html__( 'Hover/active BG Color', 'restly' ),
            ),
            'default'    => array(
                'restly_hea2_submeni_bgc'     => '#ffffff',
                'restly_hea2_submeni_textc'   => '#1d2c38',
                'restly_hea2_submeni_texthc'  => '#ffffff',
                'restly_hea2_submeni_texthbg' => '#104cba',
            ),
            'dependency' => array( 'restly_header_styles', '==', 'two', 'all' ),
        ),
        array(
            'type'       => 'submessage',
            'style'      => 'info',
            'content'    => esc_html__( 'CTA Button Option', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'two', 'all' ),
        ),
        array(
            'id'         => 'restly_show_cta2',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable CTA Button', 'restly' ),
            'subtitle'   => esc_html__( 'Enable Header CTA button if you need', 'restly' ),
            'default'    => true,
            'dependency' => array( 'restly_header_styles', '==', 'two', 'all' ),
        ),
        array(
            'id'          => 'restly_cta_bg2',
            'type'        => 'color',
            'title'       => esc_html__( 'CTA Button Bg', 'restly' ),
            'subtitle'    => esc_html__( 'Add CTA Button Background Color', 'restly' ),
            'default'     => '#104cba',
            'output'      => '.header-two .button .theme-btns',
            'output_mode' => 'background-color',
            'dependency'  => array( 'restly_header_styles|restly_show_cta2', '==|==', 'two|true', 'all' ),
        ),
        array(
            'id'          => 'restly_cta_bgh2',
            'type'        => 'color',
            'title'       => esc_html__( 'CTA Button Hover Bg', 'restly' ),
            'subtitle'    => esc_html__( 'Add CTA Button Hover Background Color', 'restly' ),
            'default'     => '#1d2c38',
            'output'      => '.header-two .button .theme-btns:hover',
            'output_mode' => 'background-color',
            'dependency'  => array( 'restly_header_styles|restly_show_cta2', '==|==', 'two|true', 'all' ),
        ),
        array(
            'id'         => 'restly_cta2_text_color',
            'type'       => 'link_color',
            'title'      => esc_html__( 'CTA Button Text Color', 'restly' ),
            'subtitle'   => esc_html__( 'Add CTA Button Text Hover and Normal Color', 'restly' ),
            'output'     => '.header-two .button .theme-btns',
            'dependency' => array( 'restly_header_styles|restly_show_cta2', '==|==', 'two|true', 'all' ),
            'default'    => array(
                'color' => '#ffffff',
                'hover' => '#ffffff',
            ),
        ),
        /////////////////////////
        // Header Three ////////
        ///////////////////////
        array(
            'id'         => 'restly_show_hlogo3',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable Logo', 'restly' ),
            'subtitle'   => esc_html__( 'Enable Logo Options if you need', 'restly' ),
            'default'    => true,
            'dependency' => array( 'restly_header_styles', '==', 'three', 'all' ),
        ),
        array(
            'id'         => 'restly_logo3',
            'type'       => 'media',
            'title'      => esc_html__( 'SIte Logo', 'restly' ),
            'subtitle'   => esc_html__( 'Upload Header Logo if you do not use Wordpress Default logo option ', 'restly' ),
            'library'    => 'image',
            'dependency' => array( 'restly_header_styles|restly_show_hlogo3', '==|==', 'three|true', 'all' ),
        ),

        array(
            'type'       => 'submessage',
            'style'      => 'success',
            'content'    => esc_html__( 'Top Header Options', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'three', 'all' ),
        ),
        array(
            'id'         => 'restly_show_top_header3',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable Top Header', 'restly' ),
            'subtitle'   => esc_html__( 'Enable Top Header Option', 'restly' ),
            'default'    => true,
            'dependency' => array( 'restly_header_styles', '==', 'three', 'all' ),
        ),
        array(
            'id'         => 'restly_top_header3_bg',
            'type'       => 'background',
            'title'      => esc_html__( 'Background', 'restly' ),
            'subtitle'   => esc_html__( 'Add Background Color or Image', 'restly' ),
            'dependency' => array( 'restly_header_styles|restly_show_top_header2', '==|', 'three|true', 'all' ),
            'default'    => array(
                'background-color' => '#104cba',
            ),
            'output'     => '.header-three .header-top',
        ),
        array(
            'id'         => 'restly_top_header3_label_c',
            'type'       => 'color',
            'title'      => esc_html__( 'Label Color', 'restly' ),
            'subtitle'   => esc_html__( 'Add Color for Header top Label', 'restly' ),
            'default'    => '#ffffff',
            'dependency' => array( 'restly_header_styles|restly_show_top_header3', '==|', 'three|true', 'all' ),
            'output'     => '.header-three .header-top ul li span',
        ),
        array(
            'id'         => 'restly_top_header3_text_c',
            'type'       => 'color',
            'title'      => esc_html__( 'Text Color', 'restly' ),
            'subtitle'   => esc_html__( 'Add Color for Header top Content', 'restly' ),
            'default'    => '#ffffff',
            'output'     => '.header-three .header-top ul li',
            'dependency' => array( 'restly_header_styles|restly_show_top_header2', '==|', 'three|true', 'all' ),
        ),
        array(
            'id'         => 'restly_top_header3_icon_c',
            'type'       => 'color',
            'title'      => esc_html__( 'Icon Color', 'restly' ),
            'subtitle'   => esc_html__( 'Withour Link Icon Color', 'restly' ),
            'default'    => '#ffffff',
            'output'     => '.header-three .office-time i',
            'dependency' => array( 'restly_header_styles|restly_show_top_header3', '==|', 'three|true', 'all' ),
        ),
        array(
            'id'         => 'restly_top_header3_link_c',
            'type'       => 'link_color',
            'title'      => esc_html__( 'Link Color', 'restly' ),
            'subtitle'   => esc_html__( 'Add Color for Header top Links Normal and Hover', 'restly' ),
            'output'     => '.header-three .header-top ul li a',
            'default'    => array(
                'color' => '#ffffff',
                'hover' => '#1d2c38',
            ),
            'dependency' => array( 'restly_header_styles|restly_show_top_header3', '==|', 'three|true', 'all' ),
        ),
        array(
            'type'       => 'submessage',
            'style'      => 'success',
            'content'    => esc_html__( 'Menu Section Options', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'three', 'all' ),
        ),
        array(
            'id'         => 'restly_top_header3_menu_ncolors',
            'type'       => 'link_color',
            'title'      => esc_html__( 'Menu Color', 'restly' ),
            'subtitle'   => esc_html__( 'Nav Menu Normal and Hover Color', 'restly' ),
            'output'     => '.header-three .main-navigation ul li a',
            'dependency' => array( 'restly_header_styles', '==', 'three', 'all' ),
            'default'    => array(
                'color' => '#ffffff',
                'hover' => '#b0c2d7',
            ),
        ),
        array(
            'id'          => 'restly_header3_border_color',
            'type'        => 'color',
            'title'       => esc_html__( 'Border Color', 'restly' ),
            'subtitle'    => esc_html__( 'Add Header Border Color', 'restly' ),
            'dependency'  => array( 'restly_header_styles', '==', 'three', 'all' ),
            'output_mode' => 'border-color',
            'output'      => '.header-three .main-header',
        ),
        array(
            'id'         => 'restly_header3_menu_bg',
            'type'       => 'background',
            'title'      => esc_html__( 'Background', 'restly' ),
            'subtitle'   => esc_html__( 'Add Background Color for Menu Area', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'three', 'all' ),
            'output'     => '.header-three .header-three .main-header.header-fluid .navbar',
        ),
        array(
            'type'       => 'submessage',
            'style'      => 'info',
            'content'    => esc_html__( 'Sub menu Options', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'three', 'all' ),
        ),
        array(
            'id'         => 'restly_header3_menu_bg',
            'type'       => 'color_group',
            'title'      => esc_html__( 'Sub menu Colors', 'restly' ),
            'subtitle'   => esc_html__( 'Add SubMenu Color', 'restly' ),
            'options'    => array(
                'restly_hea3_submeni_bgc'     => esc_html__( 'Box Background', 'restly' ),
                'restly_hea3_submeni_textc'   => esc_html__( 'Text Color', 'restly' ),
                'restly_hea3_submeni_texthc'  => esc_html__( 'Text Hover/active Color', 'restly' ),
                'restly_hea3_submeni_texthbg' => esc_html__( 'Hover/active BG Color', 'restly' ),
            ),
            'default'    => array(
                'restly_hea3_submeni_bgc'     => '#ffffff',
                'restly_hea3_submeni_textc'   => '#1d2c38',
                'restly_hea3_submeni_texthc'  => '#ffffff',
                'restly_hea3_submeni_texthbg' => '#104cba',
            ),
            'dependency' => array( 'restly_header_styles', '==', 'three', 'all' ),
        ),
        array(
            'type'       => 'submessage',
            'style'      => 'info',
            'content'    => esc_html__( 'CTA Button Option', 'restly' ),
            'dependency' => array( 'restly_header_styles', '==', 'three', 'all' ),
        ),
        array(
            'id'         => 'restly_show_cta3',
            'type'       => 'switcher',
            'title'      => esc_html__( 'Enable CTA Button', 'restly' ),
            'subtitle'   => esc_html__( 'Enable Header CTA button if you need', 'restly' ),
            'default'    => true,
            'dependency' => array( 'restly_header_styles', '==', 'three', 'all' ),
        ),
        array(
            'id'          => 'restly_cta_bg3',
            'type'        => 'color',
            'title'       => esc_html__( 'CTA Button Bg', 'restly' ),
            'subtitle'    => esc_html__( 'Add CTA Button Background Color', 'restly' ),
            'default'     => '#104cba',
            'output'      => '.header-three .button .theme-btns',
            'output_mode' => 'background-color',
            'dependency'  => array( 'restly_header_styles|restly_show_cta3', '==|==', 'three|true', 'all' ),
        ),
        array(
            'id'          => 'restly_cta_bgh3',
            'type'        => 'color',
            'title'       => esc_html__( 'CTA Button Hover Bg', 'restly' ),
            'subtitle'    => esc_html__( 'Add CTA Button Hover Background Color', 'restly' ),
            'default'     => '#1d2c38',
            'output'      => '.header-three .button .theme-btns:hover',
            'output_mode' => 'background-color',
            'dependency'  => array( 'restly_header_styles|restly_show_cta3', '==|==', 'three|true', 'all' ),
        ),
        array(
            'id'         => 'restly_cta3_text_color',
            'type'       => 'link_color',
            'title'      => esc_html__( 'CTA Button Text Color', 'restly' ),
            'subtitle'   => esc_html__( 'Add CTA Button Text Hover and Normal Color', 'restly' ),
            'output'     => '.header-three .button .theme-btns',
            'dependency' => array( 'restly_header_styles|restly_show_cta3', '==|==', 'three|true', 'all' ),
            'default'    => array(
                'color' => '#ffffff',
                'hover' => '#ffffff',
            ),
        ),
    ),
) );
// Header Button
CSF::createSection( $restlyThemeOption, array(
    'parent' => 'restly_header_settings',
    'title'  => esc_html__( 'Header CTA Button', 'restly' ),
    'icon'   => 'fas fa-arrow-right',
    'fields' => array(
        array(
            'id'       => 'restly_cta_text',
            'type'     => 'text',
            'title'    => esc_html__( 'Button Text', 'restly' ),
            'subtitle' => esc_html__( 'Add Button Text for header', 'restly' ),
            'default'  => esc_html__( 'Meet With Us', 'restly' ),
        ),
        array(
            'id'          => 'restly_cta_select',
            'type'        => 'select',
            'title'       => esc_html__( 'Select Link Options', 'restly' ),
            'subtitle'    => esc_html__( 'Select Button option', 'restly' ),
            'placeholder' => esc_html__( 'Select an option', 'restly' ),
            'options'     => array(
                '1' => esc_html__( 'Extranal', 'restly' ),
                '2' => esc_html__( 'Page', 'restly' ),
            ),
            'default'     => '1',
        ),
        array(
            'id'         => 'restly_cta_link',
            'type'       => 'text',
            'title'      => esc_html__( 'CTA Link', 'restly' ),
            'subtitle'   => esc_html__( 'Add Extranla Link Here.', 'restly' ),
            'default'    => esc_html__( '#', 'restly' ),
            'dependency' => array( 'restly_cta_select', '==', '1', 'all' ),

        ),
        array(
            'id'          => 'restly_cta_page',
            'type'        => 'select',
            'title'       => esc_html__( 'Select Page', 'restly' ),
            'subtitle'    => esc_html__( 'Select Page link for button', 'restly' ),
            'placeholder' => esc_html__( 'Select a page', 'restly' ),
            'dependency'  => array( 'restly_cta_select', '==', '2', 'all' ),
            'options'     => 'pages',
            'query_args'  => array(
                'posts_per_page' => -1,
            ),
        ),
    ),
) );

// End Header Button